version: '3.5'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    env_file:
      - .env
    volumes:
      - .:/home/app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.FE
    ports:
      - 3001:3001
